const data=[
    {
        id:1,
        title:"Blanket",
        price:"1000",
        discount:"10"
    },
    {
        id:2,
        title:"Blanket",
        price:"1000",
        discount:"10"
    },
    {
        id:3,
        title:"Blanket",
        price:"1000",
        discount:"10"
    },
    {
        id:4,
        title:"Blanket",
        price:"1000",
        discount:"10"
    },
    {
        id:5,
        title:"Blanket",
        price:"2000",
        discount:"50"
    },
    {
        id:6,
        title:"Blanket",
        price:"1000",
        discount:"10"
    },
]
export default data